### PR TITLE
Provision draft package

### PR DESCRIPTION
**Pull request by samueltwum1**
Tony's work has been imported from https://github.com/twillis449/radio_source_analysis to get the package started and released.

### CODE REVIEW

**Comment by twillis449** [comment]
Just to let you know - I'm making some modifications to the get_simple_source_list.py script. At present its finding way  too many extended sources.

**Comment by samueltwum1** [comment]
> Just to let you know - I'm making some modifications to the get_simple_source_list.py script. At present its finding way too many extended sources.

Thanks @twillis449 

Our changes for the initial release wont touch the code. The only change will be to restructure your package. So we'll continue and pull in your changes when you're done.

**Comment by bngcebetsha** [comment]
@samueltwum1 this initial step looks good to me, just for interest I went and searched the difference between `requirements.txt` and `setup.py` - https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py

**Review by bngcebetsha — APPROVED** [review]
LGTM

**Comment by samueltwum1** [comment]
> @samueltwum1 this initial step looks good to me, just for interest I went and searched the difference between `requirements.txt` and `setup.py` - https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py

Good read

**Pull request merged**
